spring:
  # VSCodeのログの設定
#  output:
#   ansi:
#     enabled: always
  # DBの設定(デプロイ時に変更)
#  datasource:
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/tenniscamp
#    username: postgres
#    password: postgres
  # DBの設定(デプロイ環境)
  datasource:
    driver-class-name: org.postgresql.Driver
    url: spring.datasource.url=jdbc:postgresql://ec2-34-225-162-157.compute-1.amazonaws.com:5432/d81p5de6ma22hm?sslmode=require
    username: ihkkxpraeoohhr
    password: b1958c30f373af67993874df9cff744de7a3209c5e7f02b8b6a9562e6218fe1a

# ローカル環境での起動ポート番号の設定
server:
  port: 8080
  
# 環境変数(デプロイ時に変更)
#ローカル環境のOrigin
environments:
  originUrl: http://localhost:8888
  
#  originUrl: https://tenniscamp-782ef.web.app/

path:
  uploadPath: "src/main/resources/static/images/"