spring:
  # VSCodeのログの設定
#  output:
#   ansi:
#     enabled: always
  # DBの設定(デプロイ時に変更)
#  datasource:
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/tenniscamp
#    username: postgres
#    password: postgres
  # DBの設定(デプロイ環境)
  datasource:
    driver-class-name: org.postgresql.Driver
    url: spring.datasource.url=jdbc:postgresql://ec2-3-220-23-212.compute-1.amazonaws.com:5432/d4bdge6clqqi0b?sslmode=require
    username: vlsknbwbmormxo
    password: f743c006d77ab1fd34f677c7c9a098c15ce598781e6c468f9379016d379b8c36

# ローカル環境での起動ポート番号の設定
server:
  port: 8080
  
# 環境変数(デプロイ時に変更)
#ローカル環境のOrigin
environments:
#  originUrl: http://localhost:8888
  
  originUrl: https://tenniscamp-app-f734e.web.app

path:
  uploadPath: "src/main/resources/static/images/"