spring:
  # VSCodeのログの設定
#  output:
#   ansi:
#     enabled: always
  # DBの設定(デプロイ時に変更)
#  datasource:
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/tenniscamp
#    username: postgres
#    password: postgres
  # DBの設定(デプロイ環境)
  datasource:
    driverClassName: org.postgresql.Driver
    url: spring.datasource.url=jdbc:postgresql://ec2-50-16-198-4.compute-1.amazonaws.com:5432/d72hh6hk3gm0l4
    username: sxutlquffhrxzv
    password: a1fa84bdc2546be64a2fc7ba68fdb984f1563f5c1326d61bf0d082ccfb864823

# ローカル環境での起動ポート番号の設定
server:
  port: 8080
  
# 環境変数(デプロイ時に変更)
#ローカル環境のOrigin
#environments:
#  originUrl: http://localhost:8888
  
environments:
  originUrl: https://tenniscamp-782ef.web.app/

path:
  uploadPath: "src/main/resources/static/images/"